name: OoT3DR Builds

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type:'
        required: true
        type: choice
        options:
        - Dev
        - Nightly
        - Release
      version:
        description: 'Release version: (For example: 3.2)'
        required: false

jobs:
  get-changelog:
    name: Retrieve Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.1.3
        with:
          fetch-depth: 0
      - name: Get Last Nightly
        id: nightly-version
        run: |
          echo "last_nightly=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV
      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.3.1
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
          base-ref: ${{ env.last_nightly }}
    outputs:
      changelog: ${{ steps.changelog.outputs.changelog }}
      last-nightly: ${{ env.last_nightly }}

  build-cia-3dsx:
    needs: get-changelog
    name: Build CIA and 3DSX Files
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/z3dr/randotools:latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.1.3

      - name: Run Build Script
        run: |
          chmod +x linux_build_rando.sh
          chmod +x write_build_id.sh
          source write_build_id.sh ${{ github.event.inputs.build_type }} ${{ github.event.inputs.version }}
          ./linux_build_rando.sh
          echo "tag_name=$TAG_NAME" >> $GITHUB_ENV

      - if: ${{ github.event.inputs.build_type != 'Release' }}
        name: Create Pre-release
        uses: ncipollo/release-action@v1.14.0
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          artifacts: "OoT3D_Randomizer.cia,OoT3D_Randomizer.3dsx,cia.png,3dsx.png"
          prerelease: true
          commit: "${{ github.sha }}"
          tag: "${{ env.tag_name }}"
          name: "${{ env.tag_name }}"
          body: |
            This release is a development build containing the following features that have not yet been merged into the main branch:
            - Add Gloom Mode setting
            - Update appearance for soulless flying traps
            - Bug fixes for Enemy Randomizer

            Please note that these are DEVELOPMENT builds and may not be entirely stable.
            When reporting issues, please mention the six character commit listed in the randomizer menu.
            You can use the FBI homebrew application to install the randomizer using either of these QR codes.
            CIA QR Code:
            ![CIA Download](https://github.com/${{ github.repository }}/releases/download/${{ env.tag_name }}/cia.png)
            3DSX QR Code:
            ![CIA Download](https://github.com/${{ github.repository }}/releases/download/${{ env.tag_name }}/3dsx.png)

            Changes Since [${{ needs.get-changelog.outputs.last-nightly }}](https://github.com/${{ github.repository }}/releases/tag/${{ needs.get-changelog.outputs.last-nightly }}) 🛠:
            ${{ needs.get-changelog.outputs.changelog }}


      - if: ${{ github.event.inputs.build_type == 'Release' }}
        name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          artifacts: "OoT3D_Randomizer.cia,OoT3D_Randomizer.3dsx,cia.png,3dsx.png"
          prerelease: false
          commit: "${{ github.sha }}"
          tag: "${{ env.tag_name }}"
          name: "${{ env.tag_name }}"
          body: |
            ${{ github.event.inputs.version }} Changes:
            - Please check back later for a full list of changes.

            When reporting issues, please mention the six character commit listed in the randomizer menu.
            You can use the FBI homebrew application to install the randomizer using either of these QR codes.
            CIA QR Code:
            ![CIA Download](https://github.com/${{ github.repository }}/releases/download/${{ env.tag_name }}/cia.png)
            3DSX QR Code:
            ![CIA Download](https://github.com/${{ github.repository }}/releases/download/${{ env.tag_name }}/3dsx.png)
